export const themeData = JSON.parse("{\"blog\":{\"description\":\"考古的\",\"intro\":\"\",\"medias\":{}},\"encrypt\":{\"config\":{\"/guide/encrypt.html\":[\"$2a$10$4N.PNDoLdmpb2WaMX8O4JO3a4Vz3XYjjslMVn2E908v/guVaGKYmW\"]}},\"pure\":false,\"darkmode\":\"disable\",\"themeColor\":false,\"fullscreen\":false,\"locales\":{\"/\":{\"blog\":{},\"repoDisplay\":true,\"navbarIcon\":true,\"navbarAutoHide\":\"mobile\",\"hideSiteNameonMobile\":true,\"sidebar\":[\"/slide\",{\"text\":\"考古\",\"icon\":\"guyizhi\",\"prefix\":\"/archaeology/\",\"link\":\"/archaeology/\",\"children\":\"structure\"},{\"text\":\"文化遺產\",\"icon\":\"zhihuiwenwu1\",\"prefix\":\"/cultural-heritage/\",\"link\":\"/cultural-heritage/\",\"children\":\"structure\"},{\"text\":\"檔案\",\"icon\":\"dataarchive\",\"prefix\":\"/archive/\",\"link\":\"/archive/\",\"children\":\"structure\"},{\"text\":\"傳理\",\"icon\":\"xinwen\",\"prefix\":\"/communication/\",\"link\":\"/communication/\",\"children\":\"structure\"}],\"sidebarIcon\":true,\"headerDepth\":2,\"lang\":\"zh-TW\",\"navbarLocales\":{\"langName\":\"繁體中文\",\"selectLangText\":\"選擇語言\",\"selectLangAriaLabel\":\"選擇語言\"},\"metaLocales\":{\"author\":\"作者\",\"date\":\"寫作日期\",\"origin\":\"原創\",\"views\":\"訪問量\",\"category\":\"分類\",\"tag\":\"標籤\",\"readingTime\":\"閱讀時間\",\"words\":\"字數\",\"toc\":\"此頁內容\",\"prev\":\"上一頁\",\"next\":\"下一頁\",\"lastUpdated\":\"上次編輯於\",\"contributors\":\"貢獻者\",\"editLink\":\"編輯此頁\"},\"blogLocales\":{\"article\":\"文章\",\"articleList\":\"文章列表\",\"category\":\"分類\",\"tag\":\"標籤\",\"timeline\":\"時間軸\",\"timelineTitle\":\"昨日不在\",\"all\":\"全部\",\"intro\":\"個人介紹\",\"star\":\"收藏\",\"slides\":\"幻燈片\",\"encrypt\":\"加密\"},\"paginationLocales\":{\"prev\":\"上一頁\",\"next\":\"下一頁\",\"navigate\":\"跳轉到\",\"action\":\"前往\",\"errorText\":\"請輸入 1 到 $page 之前的頁碼！\"},\"outlookLocales\":{\"themeColor\":\"主題色\",\"darkmode\":\"主題模式\",\"fullscreen\":\"全屏\"},\"encryptLocales\":{\"title\":\"頁面已加密\",\"placeholder\":\"輸入密碼\",\"remember\":\"記憶密碼\",\"errorHint\":\"請輸入正確密碼\"},\"routeLocales\":{\"404msg\":[\"這裡什麼也沒有\",\"我們是怎麼來到這兒的？\",\"這 是 四 零 四 !\",\"看起来你訪問了一個失效的鏈結\"],\"back\":\"返回上一頁\",\"home\":\"帶我回家\",\"openInNewWindow\":\"Open in new window\"},\"author\":{\"name\":\"NGKinchung\",\"url\":\"https://citenote.github.io\"},\"logo\":\"/logo.svg\",\"repo\":\"citenote/citenote.github.io\",\"editLink\":false,\"displayFooter\":true,\"navbar\":[{\"text\":\"考古\",\"icon\":\"\",\"link\":\"/archaeology/\"},{\"text\":\"文化遺產\",\"icon\":\"\",\"link\":\"/cultural-heritage/\"},{\"text\":\"檔案\",\"icon\":\"\",\"link\":\"/archive/\"},{\"text\":\"傳理\",\"icon\":\"\",\"link\":\"/communication/\"}],\"footer\":\"\",\"pageInfo\":[\"Author\",\"Original\",\"Date\",\"Category\",\"Tag\",\"ReadingTime\"]}}}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updateThemeData) {
    __VUE_HMR_RUNTIME__.updateThemeData(themeData)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ themeData }) => {
    __VUE_HMR_RUNTIME__.updateThemeData(themeData)
  })
}
