export const data = JSON.parse("{\"key\":\"v-452b2d08\",\"path\":\"/archaeology/site-and-culture/yin-ruins.html\",\"title\":\"殷墟遺址\",\"lang\":\"zh-TW\",\"frontmatter\":{\"lang\":\"zh-TW\",\"author\":\"NG Kinchung\",\"date\":\"2022-01-22T00:00:00.000Z\",\"summary\":\"殷墟遺址 簡報、報告\\r\\\" 資料依發表年份排序。\\\" 綜合 1. 傅斯年：〈本所發掘殷虛之經過〉，載李濟總編輯：《安陽發掘報告（第二期）》，中央研究所歷史語言研究所，1930年，第387-404頁。 2. 郭寶鈞：〈一九五〇年春殷墟發掘報告〉，《中國考古學報》1951年第5冊，第1-61頁。 3. 中國社會科學院考古研究所安陽隊：〈河南安陽洹河流域的考古調查〉，\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://citenote.github.io/archaeology/site-and-culture/yin-ruins.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"研究資料類編\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"殷墟遺址\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-TW\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"NG Kinchung\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2022-01-22T00:00:00.000Z\"}]]},\"excerpt\":\"\",\"headers\":[{\"level\":2,\"title\":\"簡報、報告\",\"slug\":\"簡報、報告\",\"children\":[{\"level\":3,\"title\":\"綜合\",\"slug\":\"綜合\",\"children\":[]},{\"level\":3,\"title\":\"小屯\",\"slug\":\"小屯\",\"children\":[]},{\"level\":3,\"title\":\"侯家莊\",\"slug\":\"侯家莊\",\"children\":[]},{\"level\":3,\"title\":\"大司空\",\"slug\":\"大司空\",\"children\":[]},{\"level\":3,\"title\":\"花園莊\",\"slug\":\"花園莊\",\"children\":[]},{\"level\":3,\"title\":\"劉家莊\",\"slug\":\"劉家莊\",\"children\":[]},{\"level\":3,\"title\":\"孝民屯\",\"slug\":\"孝民屯\",\"children\":[]},{\"level\":3,\"title\":\"西區\",\"slug\":\"西區\",\"children\":[]},{\"level\":3,\"title\":\"苗圃\",\"slug\":\"苗圃\",\"children\":[]},{\"level\":3,\"title\":\"後岡\",\"slug\":\"後岡\",\"children\":[]},{\"level\":3,\"title\":\"王裕口\",\"slug\":\"王裕口\",\"children\":[]},{\"level\":3,\"title\":\"薛家莊\",\"slug\":\"薛家莊\",\"children\":[]},{\"level\":3,\"title\":\"梅園莊\",\"slug\":\"梅園莊\",\"children\":[]},{\"level\":3,\"title\":\"洹北\",\"slug\":\"洹北\",\"children\":[]},{\"level\":3,\"title\":\"郭家莊\",\"slug\":\"郭家莊\",\"children\":[]}]},{\"level\":2,\"title\":\"年鑒\",\"slug\":\"年鑒\",\"children\":[]},{\"level\":2,\"title\":\"圖錄\",\"slug\":\"圖錄\",\"children\":[]},{\"level\":2,\"title\":\"研究\",\"slug\":\"研究\",\"children\":[{\"level\":3,\"title\":\"論文\",\"slug\":\"論文\",\"children\":[]},{\"level\":3,\"title\":\"專著\",\"slug\":\"專著\",\"children\":[]}]},{\"level\":2,\"title\":\"報道\",\"slug\":\"報道\",\"children\":[]}],\"readingTime\":{\"minutes\":30.13,\"words\":9038},\"filePathRelative\":\"archaeology/site-and-culture/yin-ruins.md\",\"localizedDate\":\"2022年1月22日\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
